name: Bot

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

env:
  LBANK_API_KEY: ${{ secrets.LBANK_API_KEY }}
  LBANK_API_SECRET: ${{ secrets.LBANK_API_SECRET }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python main.py
