name: Bot
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - env:
          GAPGPTMASKTOKENh24oc5sie19X0X: ${{ secrets.GAPGPTMASKTOKENh24oc5sie19X1X }}
          GAPGPTMASKTOKENh24oc5sie19X2X: ${{ secrets.GAPGPTMASKTOKENh24oc5sie19X3X }}
          TELE
